FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN python -c "\
from transformers import BartForConditionalGeneration, BartTokenizer, \
                         MarianMTModel, MarianTokenizer; \
BartForConditionalGeneration.from_pretrained('facebook/bart-large-cnn'); \
BartTokenizer.from_pretrained('facebook/bart-large-cnn'); \
MarianMTModel.from_pretrained('Helsinki-NLP/opus-mt-ru-en'); \
MarianTokenizer.from_pretrained('Helsinki-NLP/opus-mt-ru-en')"

COPY . .

EXPOSE 8001

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]