version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: messenger_redis
    restart: always
    ports:
      - "6379:6379"

  ml:
    build: ./ml
    container_name: messenger_ml
    restart: always
    expose:
      - "8001"
    volumes:
      - hf_cache:/root/.cache/huggingface 

  db:
    image: postgres:15-alpine
    container_name: messenger_db
    restart: always
    environment:
      POSTGRES_USER: sanzhar
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_DB: messenger_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sanzhar -d messenger_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: messenger_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      ml:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://sanzhar:your_secure_password@db:5432/messenger_db
      - REDIS_URL=redis://redis:6379/0
      - ML_SERVICE_URL=http://ml:8001
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: messenger_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80" 

volumes:
  pg_data:    
  hf_cache:  